server.port=8080
spring.application.name=matricula_ino

# ---- Datos de conexion a la base de datos PostgreSQL ----
# Cambia estos valores segun tu configuracion local (pgAdmin / psql / etc.)
db.url=jdbc:postgresql://localhost:5432/matricula_ino
db.user=postgres
db.password=postgres

spring.thymeleaf.cache=false
